const { app, BrowserWindow, ipcMain, dialog, shell } = require('electron');
const { spawn, exec } = require('child_process');
const path = require('path');
const fs = require('fs');
const Store = require('electron-store');

// Initialize electron-store for settings persistence
const store = new Store();

let mainWindow;
let pythonProcess = null;
let isDev = process.env.ELECTRON_IS_DEV === '1';

// Get the correct path for Python scripts
function getPythonPath() {
  if (isDev) {
    // In development, use the local python directory
    return path.join(__dirname, '..', 'python');
  } else {
    // In production, Python files are in resources/python
    return path.join(process.resourcesPath, 'python');
  }
}

function createWindow() {
  // Create the browser window
  mainWindow = new BrowserWindow({
    width: 900,
    height: 700,
    minWidth: 800,
    minHeight: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true
    },
    titleBarStyle: 'default',
    show: false // Don't show until ready
  });

  // Load the main page
  mainWindow.loadFile('renderer/index.html');

  // Show window when ready
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    
    if (isDev) {
      mainWindow.webContents.openDevTools();
    }
  });

  // Handle window closed
  mainWindow.on('closed', () => {
    mainWindow = null;
    // Kill Python process if running
    if (pythonProcess) {
      pythonProcess.kill();
      pythonProcess = null;
    }
  });
}

// App event handlers
app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  // On macOS, keep app running even when all windows are closed
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On macOS, re-create window when dock icon is clicked
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  // Clean up Python process
  if (pythonProcess) {
    pythonProcess.kill();
  }
});

// IPC Handlers

// Save settings to persistent storage
ipcMain.handle('save-settings', async (event, settings) => {
  try {
    store.set('settings', settings);
    
    // Also create .env file in Python directory for the Python scripts
    const pythonPath = getPythonPath();
    const envPath = path.join(pythonPath, '.env');
    
    const envContent = [
      '# Assignment Calendar Sync Configuration',
      '# Generated by Desktop App',
      '',
      `GOOGLE_CLIENT_ID=${settings.googleClientId || ''}`,
      `GOOGLE_CLIENT_SECRET=${settings.googleClientSecret || ''}`,
      `GOOGLE_CALENDAR_ID=${settings.googleCalendarId || 'primary'}`,
      '',
      `GRADESCOPE_EMAIL=${settings.gradescopeEmail || ''}`,
      `GRADESCOPE_PASSWORD=${settings.gradescopePassword || ''}`,
      '',
      `SYNC_DAYS_AHEAD=${settings.syncDaysAhead || 30}`,
      `DEFAULT_REMINDER_MINUTES=${settings.reminderMinutes || 60}`,
      `HEADLESS_BROWSER=true`,
      `DEBUG_MODE=${settings.debugMode || false}`,
      `TIMEZONE=${settings.timezone || 'America/New_York'}`,
      ''
    ].join('\n');
    
    fs.writeFileSync(envPath, envContent);
    
    return { success: true };
  } catch (error) {
    console.error('Error saving settings:', error);
    return { success: false, error: error.message };
  }
});

// Load settings from persistent storage
ipcMain.handle('load-settings', async (event) => {
  try {
    const settings = store.get('settings', {
      googleClientId: '',
      googleClientSecret: '',
      googleCalendarId: 'primary',
      gradescopeEmail: '',
      gradescopePassword: '',
      syncDaysAhead: 30,
      reminderMinutes: 60,
      debugMode: false,
      timezone: 'America/New_York'
    });
    
    return { success: true, settings };
  } catch (error) {
    console.error('Error loading settings:', error);
    return { success: false, error: error.message };
  }
});

// Test Python environment
ipcMain.handle('test-python', async (event) => {
  return new Promise((resolve) => {
    exec('python3 --version', (error, stdout, stderr) => {
      if (error) {
        resolve({ success: false, error: 'Python 3 not found. Please install Python 3.7+' });
      } else {
        resolve({ success: true, version: stdout.trim() });
      }
    });
  });
});

// Test configuration
ipcMain.handle('test-config', async (event) => {
  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const configScript = path.join(pythonPath, 'config.py');
    
    const python = spawn('python3', [configScript], {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    let error = '';

    python.stdout.on('data', (data) => {
      output += data.toString();
    });

    python.stderr.on('data', (data) => {
      error += data.toString();
    });

    python.on('close', (code) => {
      if (code === 0) {
        resolve({ success: true, output });
      } else {
        resolve({ success: false, error: error || 'Configuration test failed' });
      }
    });

    // Timeout after 30 seconds
    setTimeout(() => {
      python.kill();
      resolve({ success: false, error: 'Configuration test timed out' });
    }, 30000);
  });
});

// Run sync process
ipcMain.handle('run-sync', async (event, options = {}) => {
  // Kill existing process if running
  if (pythonProcess) {
    pythonProcess.kill();
    pythonProcess = null;
  }

  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const mainScript = path.join(pythonPath, 'main.py');
    
    // Build command line arguments
    const args = [mainScript];
    if (options.dryRun) args.push('--dry-run');
    if (options.verbose) args.push('--verbose');
    if (options.days) args.push('--days', options.days.toString());
    if (options.all) args.push('--all');

    pythonProcess = spawn('python3', args, {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    let hasError = false;

    // Send real-time output to renderer
    pythonProcess.stdout.on('data', (data) => {
      const text = data.toString();
      output += text;
      event.sender.send('sync-output', { type: 'stdout', data: text });
    });

    pythonProcess.stderr.on('data', (data) => {
      const text = data.toString();
      output += text;
      hasError = true;
      event.sender.send('sync-output', { type: 'stderr', data: text });
    });

    pythonProcess.on('close', (code) => {
      pythonProcess = null;
      
      if (code === 0) {
        resolve({ success: true, output, code });
      } else {
        resolve({ success: false, output, code, error: hasError });
      }
      
      event.sender.send('sync-complete', { success: code === 0, code, output });
    });

    pythonProcess.on('error', (error) => {
      pythonProcess = null;
      const errorMsg = `Failed to start Python process: ${error.message}`;
      resolve({ success: false, error: errorMsg });
      event.sender.send('sync-complete', { success: false, error: errorMsg });
    });

    // Timeout after 10 minutes
    setTimeout(() => {
      if (pythonProcess) {
        pythonProcess.kill();
        pythonProcess = null;
        const errorMsg = 'Sync process timed out after 10 minutes';
        resolve({ success: false, error: errorMsg });
        event.sender.send('sync-complete', { success: false, error: errorMsg });
      }
    }, 600000);
  });
});

// Cancel running sync
ipcMain.handle('cancel-sync', async (event) => {
  if (pythonProcess) {
    pythonProcess.kill();
    pythonProcess = null;
    return { success: true, message: 'Sync cancelled' };
  }
  return { success: false, message: 'No sync process running' };
});

// Open external links
ipcMain.handle('open-external', async (event, url) => {
  try {
    await shell.openExternal(url);
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// Show save dialog
ipcMain.handle('show-save-dialog', async (event, options) => {
  try {
    const result = await dialog.showSaveDialog(mainWindow, options);
    return result;
  } catch (error) {
    return { canceled: true, error: error.message };
  }
});

// Show open dialog
ipcMain.handle('show-open-dialog', async (event, options) => {
  try {
    const result = await dialog.showOpenDialog(mainWindow, options);
    return result;
  } catch (error) {
    return { canceled: true, error: error.message };
  }
});

// Get app version
ipcMain.handle('get-app-info', async (event) => {
  return {
    version: app.getVersion(),
    name: app.getName(),
    isDev: isDev
  };
});