const { app, BrowserWindow, ipcMain, dialog, shell } = require('electron');
const { spawn, exec } = require('child_process');
const path = require('path');
const fs = require('fs');
const os = require('os');

// Simple JSON-based settings storage
const settingsPath = path.join(os.homedir(), '.assignment-calendar-sync.json');

function loadSettings() {
  try {
    if (fs.existsSync(settingsPath)) {
      return JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    }
  } catch (error) {
    console.error('Error loading settings:', error);
  }
  return {
    gradescopeUseSSO: true,
    gradescopeEmail: '',
    gradescopePassword: '',
    syncDaysAhead: 30,
    timezone: 'America/New_York',
    firstRun: true
  };
}

function saveSettings(settings) {
  try {
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    return true;
  } catch (error) {
    console.error('Error saving settings:', error);
    return false;
  }
}

let mainWindow;
let pythonProcess = null;
let isDev = process.env.ELECTRON_IS_DEV === '1' || !app.isPackaged;

// Get the correct path for Python scripts
function getPythonPath() {
  if (isDev) {
    return path.join(__dirname, '..', 'python');
  } else {
    // In production, look for bundled Python first, then fall back to system
    const bundledPath = path.join(process.resourcesPath, 'python');
    if (fs.existsSync(bundledPath)) {
      return bundledPath;
    }
    // Fall back to same directory as executable
    return path.join(path.dirname(process.execPath), 'python');
  }
}

// Create .env file for Python scripts
function createEnvFile(settings) {
  const pythonPath = getPythonPath();
  
  console.log(`Python path detected as: ${pythonPath}`);
  console.log(`isDev: ${isDev}`);
  console.log(`app.isPackaged: ${app.isPackaged}`);
  
  // Check if Python directory exists
  if (!fs.existsSync(pythonPath)) {
    console.error(`Python directory does not exist: ${pythonPath}`);
    return false;
  }
  
  const envPath = path.join(pythonPath, '.env');
  
  const envContent = [
    '# Assignment Calendar Sync Configuration',
    '# Generated by Desktop App',
    '',
    `GRADESCOPE_USE_SSO=${settings.gradescopeUseSSO}`,
    `GRADESCOPE_EMAIL=${settings.gradescopeEmail || ''}`,
    `GRADESCOPE_PASSWORD=${settings.gradescopePassword || ''}`,
    '',
    `NOTION_API_TOKEN=${settings.notionToken || ''}`,
    `NOTION_DATABASE_ID=${settings.notionDatabase || ''}`,
    '',
    `SYNC_DAYS_AHEAD=${settings.syncDaysAhead || 30}`,
    `TARGET_SEMESTER=${settings.targetSemester || 'current'}`,
    `DEFAULT_REMINDER_MINUTES=60`,
    `HEADLESS_BROWSER=false`,
    `DEBUG_MODE=false`,
    `TIMEZONE=${settings.timezone || 'America/New_York'}`,
    '',
    '# Not needed for ICS mode',
    'GOOGLE_CLIENT_ID=',
    'GOOGLE_CLIENT_SECRET=',
    'GOOGLE_CALENDAR_ID=primary'
  ].join('\n');
  
  try {
    fs.writeFileSync(envPath, envContent);
    console.log(`Successfully created .env file at: ${envPath}`);
    return true;
  } catch (error) {
    console.error('Error creating .env file:', error);
    return false;
  }
}

function createWindow() {
  // Create the browser window
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 800,
    minWidth: 900,
    minHeight: 700,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true
    },
    titleBarStyle: 'default',
    show: false,
    icon: path.join(__dirname, '../assets/icon.png') // We'll create this
  });

  // Load the simple interface
  mainWindow.loadFile('renderer/simple.html');

  // Show window when ready
  mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    
    if (isDev) {
      mainWindow.webContents.openDevTools();
    }
  });

  // Handle window closed
  mainWindow.on('closed', () => {
    mainWindow = null;
    // Kill Python process if running
    if (pythonProcess) {
      pythonProcess.kill();
      pythonProcess = null;
    }
  });
}

// App event handlers
app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  // On macOS, keep app running even when all windows are closed
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On macOS, re-create window when dock icon is clicked
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', () => {
  // Clean up Python process
  if (pythonProcess) {
    pythonProcess.kill();
  }
});

// IPC Handlers

// Save settings
ipcMain.handle('save-settings', async (event, settings) => {
  try {
    const success = saveSettings(settings);
    if (success) {
      createEnvFile(settings);
    }
    return { success };
  } catch (error) {
    console.error('Error saving settings:', error);
    return { success: false, error: error.message };
  }
});

// Load settings
ipcMain.handle('load-settings', async (event) => {
  try {
    const settings = loadSettings();
    return { success: true, settings };
  } catch (error) {
    console.error('Error loading settings:', error);
    return { success: false, error: error.message };
  }
});

// Test Python environment
ipcMain.handle('test-python', async (event) => {
  return new Promise((resolve) => {
    exec('python3 --version', (error, stdout, stderr) => {
      if (error) {
        resolve({ success: false, error: 'Python 3 not found. Please install Python 3.7+' });
      } else {
        resolve({ success: true, version: stdout.trim() });
      }
    });
  });
});

// Test configuration
ipcMain.handle('test-config', async (event) => {
  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const configScript = path.join(pythonPath, 'config.py');
    
    const python = spawn('python3', [configScript], {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    let error = '';

    python.stdout.on('data', (data) => {
      output += data.toString();
    });

    python.stderr.on('data', (data) => {
      error += data.toString();
    });

    python.on('close', (code) => {
      if (code === 0) {
        resolve({ success: true, output });
      } else {
        resolve({ success: false, error: error || 'Configuration test failed' });
      }
    });

    // Timeout after 30 seconds
    setTimeout(() => {
      python.kill();
      resolve({ success: false, error: 'Configuration test timed out' });
    }, 30000);
  });
});

// Run the simple sync process
ipcMain.handle('run-sync', async (event, options = {}) => {
  if (pythonProcess) {
    pythonProcess.kill();
    pythonProcess = null;
  }

  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const syncScript = path.join(pythonPath, 'combined_sync.py');
    
    // Use combined_sync.py for ICS + Notion Calendar sync
    pythonProcess = spawn('python3', [syncScript], {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    let hasError = false;

    // Send real-time output to renderer
    pythonProcess.stdout.on('data', (data) => {
      const text = data.toString();
      output += text;
      event.sender.send('sync-output', { type: 'stdout', data: text });
    });

    pythonProcess.stderr.on('data', (data) => {
      const text = data.toString();
      output += text;
      hasError = true;
      event.sender.send('sync-output', { type: 'stderr', data: text });
    });

    pythonProcess.on('close', (code) => {
      pythonProcess = null;
      
      if (code === 0) {
        resolve({ success: true, output, code });
      } else {
        resolve({ success: false, output, code, error: hasError });
      }
      
      event.sender.send('sync-complete', { success: code === 0, code, output });
    });

    pythonProcess.on('error', (error) => {
      pythonProcess = null;
      const errorMsg = `Failed to start Python process: ${error.message}`;
      resolve({ success: false, error: errorMsg });
      event.sender.send('sync-complete', { success: false, error: errorMsg });
    });

    // Timeout after 10 minutes
    setTimeout(() => {
      if (pythonProcess) {
        pythonProcess.kill();
        pythonProcess = null;
        const errorMsg = 'Sync process timed out after 10 minutes';
        resolve({ success: false, error: errorMsg });
        event.sender.send('sync-complete', { success: false, error: errorMsg });
      }
    }, 600000);
  });
});

// Cancel running sync
ipcMain.handle('cancel-sync', async (event) => {
  if (pythonProcess) {
    pythonProcess.kill();
    pythonProcess = null;
    return { success: true, message: 'Sync cancelled' };
  }
  return { success: false, message: 'No sync process running' };
});

// Open external links
ipcMain.handle('open-external', async (event, url) => {
  try {
    await shell.openExternal(url);
    return { success: true };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// Show save dialog
ipcMain.handle('show-save-dialog', async (event, options) => {
  try {
    const result = await dialog.showSaveDialog(mainWindow, options);
    return result;
  } catch (error) {
    return { canceled: true, error: error.message };
  }
});

// Show open dialog
ipcMain.handle('show-open-dialog', async (event, options) => {
  try {
    const result = await dialog.showOpenDialog(mainWindow, options);
    return result;
  } catch (error) {
    return { canceled: true, error: error.message };
  }
});

// Fetch courses for selection
ipcMain.handle('fetch-courses', async (event) => {
  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const fetchScript = path.join(pythonPath, 'fetch_courses.py');
    
    const python = spawn('python3', [fetchScript], {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    let hasError = false;

    // Send real-time output to renderer
    python.stdout.on('data', (data) => {
      const text = data.toString();
      output += text;
      event.sender.send('course-fetch-output', { type: 'stdout', data: text });
    });

    python.stderr.on('data', (data) => {
      const text = data.toString();
      output += text;
      hasError = true;
      event.sender.send('course-fetch-output', { type: 'stderr', data: text });
    });

    python.on('close', (code) => {
      if (code === 0) {
        // Try to parse course data from output
        try {
          const lines = output.split('\n');
          const dataLine = lines.find(line => line.startsWith('COURSE_DATA:'));
          if (dataLine) {
            const courseData = JSON.parse(dataLine.replace('COURSE_DATA:', ''));
            resolve({ success: true, courses: courseData });
          } else {
            resolve({ success: false, error: 'No course data found in output' });
          }
        } catch (e) {
          resolve({ success: false, error: `Failed to parse course data: ${e.message}` });
        }
      } else {
        resolve({ success: false, error: hasError ? 'Script failed with errors' : 'Script exited with error code' });
      }
      
      event.sender.send('course-fetch-complete', { success: code === 0, code, output });
    });

    python.on('error', (error) => {
      const errorMsg = `Failed to start Python process: ${error.message}`;
      resolve({ success: false, error: errorMsg });
      event.sender.send('course-fetch-complete', { success: false, error: errorMsg });
    });

    // Timeout after 5 minutes
    setTimeout(() => {
      python.kill();
      const errorMsg = 'Course fetch timed out after 5 minutes';
      resolve({ success: false, error: errorMsg });
      event.sender.send('course-fetch-complete', { success: false, error: errorMsg });
    }, 300000);
  });
});

// Save course selection
ipcMain.handle('save-course-selection', async (event, selectedCourses) => {
  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const saveScript = path.join(pythonPath, 'save_course_selection.py');
    
    const python = spawn('python3', [saveScript, JSON.stringify(selectedCourses)], {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    
    python.stdout.on('data', (data) => {
      output += data.toString();
    });

    python.stderr.on('data', (data) => {
      output += data.toString();
    });

    python.on('close', (code) => {
      if (code === 0) {
        resolve({ success: true, message: 'Course selection saved successfully' });
      } else {
        resolve({ success: false, error: 'Failed to save course selection' });
      }
    });

    python.on('error', (error) => {
      resolve({ success: false, error: error.message });
    });
  });
});

// Load course selection
ipcMain.handle('load-course-selection', async (event) => {
  return new Promise((resolve) => {
    const pythonPath = getPythonPath();
    const loadScript = path.join(pythonPath, 'load_course_selection.py');
    
    const python = spawn('python3', [loadScript], {
      cwd: pythonPath,
      env: { ...process.env, PYTHONPATH: pythonPath }
    });

    let output = '';
    
    python.stdout.on('data', (data) => {
      output += data.toString();
    });

    python.on('close', (code) => {
      if (code === 0) {
        try {
          const lines = output.split('\n');
          const dataLine = lines.find(line => line.startsWith('SELECTION_DATA:'));
          if (dataLine) {
            const selectionData = JSON.parse(dataLine.replace('SELECTION_DATA:', ''));
            resolve({ success: true, selection: selectionData });
          } else {
            resolve({ success: true, selection: [] }); // No selection saved yet
          }
        } catch (e) {
          resolve({ success: false, error: `Failed to parse selection data: ${e.message}` });
        }
      } else {
        resolve({ success: false, error: 'Failed to load course selection' });
      }
    });

    python.on('error', (error) => {
      resolve({ success: false, error: error.message });
    });
  });
});

// Get app version
ipcMain.handle('get-app-info', async (event) => {
  return {
    version: app.getVersion(),
    name: app.getName(),
    isDev: isDev
  };
});